### ISSUE TITLE
pip install xarray-multiscale installs mypy==0.790 as well

### ISSUE THREAD

**Issue by pattonw** [JaneliaSciComp/xarray-multiscale#14]
mypy is listed as a dependency with a specific version requirement. I would expect mypy to be a dev dependency.
Also a somewhat old version of mypy since they are currently on 0.971.

**Comment by d-v-b** [comment]
mypy should indeed be a dev depedency, I can get this fixed tomorrow

**Comment by d-v-b** [comment]
well, I did get it fixed 22 days ago, but didn't publish the fix until now :)
